apiVersion: v1
kind: Service
metadata:
  name: servicetest
  labels:
    name: nginx
    app: nginx
    namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
