apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    name: nginx
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: test
      labels:
        name: nginx
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
